platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby

inputs:
- name: cookbook
- name: version
- name: old_version

outputs:
- name: cookbook-version

run:
  path: bash
  args:
    - -c
    - |
      export NEW_VERSION=$(cat ./version/number)
      export OLD_VERSION=$(cat ./old_version/number)
      cp -R cookbook/. cookbook-version
      cd cookbook-version
      echo $NEW_VERSION > VERSION
      [[ -e Berksfile.lock ]] && sed -i "s/$COOKBOOK_NAME ($OLD_VERSION)/$COOKBOOK_NAME ($NEW_VERSION)/g" Berksfile.lock
      git config user.email $GIT_EMAIL
      git config user.name $GIT_NAME
      git add .
      git commit -m "Bump to $NEW_VERSION"
